language: node_js
node_js:
  - "9"
services: docker
env:
  global: []
before_install:
  - cd frontend
  # Install Chrome (for Selenium/Nightwatch testing)
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
install:
- npm install
- npm install codecov
cache:
  directories:
    - "node_modules"
script:
#- "travis_wait 30 sleep 1800 &"
- "npm run test --coverage"
after_success:
#- "/bin/bash deploy"
#- make docker-deps-down
- codecov
