language: node_js
node_js:
  - "9"
services: docker
env:
  global: []
before_install:
- cd frontend
install:
- npm install
- npm install codecov
cache:
  directories:
    - "node_modules"
script:
#- "travis_wait 30 sleep 1800 &"
- "npm run test --coverage"
after_success:
#- "/bin/bash deploy"
#- make docker-deps-down
- codecov
